# Generated by Django 5.1.7 on 2025-05-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
