# Generated by Django 5.1.7 on 2025-05-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
