# Generated by Django 5.1.7 on 2025-06-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0012_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
