# Generated by Django 5.1.7 on 2025-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0015_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/message/'),
        ),
    ]
